server {
    listen 443 ssl;
    listen [::]:443 ssl;

    server_name maballet.42.fr;

    ssl_certificate /etc/nginx/ssl/inception.crt;
    ssl_certificate_key /etc/nginx/ssl/inception.key;

    # Protocols sécurisés exigés par le sujet (TLS v1.2 et v1.3 uniquement)
    ssl_protocols TLSv1.2 TLSv1.3;

    # Racine du site et fichiers d'index
    root /var/www/wordpress;
    index index.php index.html index.htm;

	client_max_body_size 20M;

    # Règle par défaut : chercher le fichier, sinon renvoyer une erreur 404
    location / {
        try_files $uri $uri/ =404;
    }

    # LE BLOC MAGIQUE : Redirection des fichiers .php vers le conteneur WordPress
    location ~ \.php$ {
        # Découpe l'URL pour séparer le script PHP des arguments
        fastcgi_split_path_info ^(.+\.php)(/.+)$;
        
        # Envoie la requête au conteneur 'wordpress' sur le port 9000
        fastcgi_pass wordpress:9000;
        
        # Fichier par défaut si aucun n'est spécifié
        fastcgi_index index.php;
        
        # Inclut les paramètres standards de FastCGI
        include fastcgi_params;
        
        # Donne le chemin absolu du fichier PHP à exécuter dans le conteneur WordPress
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;
    }
}