[www]
; instead of the default.conf, we choose this one with the right listen key

user = www-data
group = www-data

listen = 9000

; Gestion des processus (on reste sur du dynamique de base)
pm = dynamic
pm.max_children = 5
pm.start_servers = 2
pm.min_spare_servers = 1
pm.max_spare_servers = 3

; Nettoyage des variables d'environnement (indispensable pour que PHP lise les variables du docker-compose)
clear_env = no