FROM debian:bookworm

RUN apt-get update && apt-get upgrade -y && apt-get install -y \
    php-fpm \
    php-mysql \
	php-gd \
    wget \
    mariadb-client

# upload WP-CLI
RUN wget https://raw.githubusercontent.com/wp-cli/builds/gh-pages/phar/wp-cli.phar

# have executable file in binary system
RUN chmod +x wp-cli.phar && mv wp-cli.phar /usr/local/bin/wp

# conf fig installing wordpress
COPY ./requirements/wordpress/conf/www.conf /etc/php/8.2/fpm/pool.d/www.conf

COPY ./requirements/wordpress/tools/wp-conf.sh /usr/local/bin/wp-conf.sh
RUN chmod +x /usr/local/bin/wp-conf.sh

# going in the website folder
WORKDIR /var/www/html

EXPOSE 9000

ENTRYPOINT ["/usr/local/bin/wp-conf.sh"]